version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 324037310518.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started...
      - docker build -t animatem:latest .
      - docker tag animatem:latest 324037310518.dkr.ecr.ap-southeast-1.amazonaws.com/animatem:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 324037310518.dkr.ecr.ap-southeast-1.amazonaws.com/animatem:latest
artifacts:
  files:
    - appspec.yml
    - scripts/*